before_install:
 - ssh-keygen -P '' -f ~/.ssh/id_rsa
 - sudo apt-get install --no-install-recommends --yes openssh-server
 - cat ~/.ssh/id_rsa.pub |tee -a ~/.ssh/authorized_keys
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
notifications:
  recipients:
    - jordon@envygeeks.io
branches:
  only:
    - master
