cache: bundler
sudo: false
before_install:
- ssh-keygen -P '' -f ~/.ssh/id_rsa
- cat ~/.ssh/id_rsa.pub | tee -a ~/.ssh/authorized_keys
addons:
  apt:
    packages:
    - openssh-server
rvm:
- 2.1.8
- 2.2.4
- 2.3.0
notifications:
  recipients:
  - jordon@envygeeks.io
branches:
  only:
  - master
