before_install:
 - ssh-keygen -P '' -f ~/.ssh/id_rsa
 - sudo apt-get install --no-install-recommends --yes openssh-server
 - cat ~/.ssh/id_rsa.pub |tee -a ~/.ssh/authorized_keys
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9
notifications:
  recipients:
    - jordon@envygeeks.io
branches:
  only:
    - master
env:
  - ""
  - "WITH_ANSI=true"
